### ISSUE TITLE
Can't build app

### ISSUE THREAD

**Issue by lkalneus** [macdonst/VideoPlayer#17]
Hello!
I added VideoPlayer to Hello World PhoneGap application.

But while building I get next problems:

-dex:
      [dex] input: D:\Build\Android\PhoneGap\video\platforms\android\bin\classes
      [dex] input: D:\Build\Android\PhoneGap\video\platforms\android\libs\cordova-3.0.0.jar
      [dex] Pre-Dexing D:\Build\Android\PhoneGap\video\platforms\android\libs\cordova-3.0.0.jar -> cordova-3.0.0-dcb01b803346297fc6233e00d113c728.jar
      [dex] Converting compiled files and external libraries into D:\Build\Android\PhoneGap\video\platforms\android\bin\classes.dex...
       [dx]
       [dx] UNEXPECTED TOP-LEVEL EXCEPTION:
       [dx] com.android.dx.util.DexException: Multiple dex files define Lcom/phonegap/hello_world/HelloWorld;
       [dx]     at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:592)
       [dx]     at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:550)
       [dx]     at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:531)
Failed to find apk, make sure you project is built and there is an
 apk in <project>\bin.  To build your project use '<project>\cordova\build'

Please advise solution to that problem?

**Comment by macdonst** [comment]
You've got this class com/phonegap/hello_world/HelloWorld in your build path twice. Check for any included jars that may also have that class in it.
